//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JIM_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Compras = new HashSet<Compra>();
        }
    
        public int IdCliente { get; set; }
        public string PrimeiroNome { get; set; }
        public string UltimoNome { get; set; }
        public System.DateTime DataNasc { get; set; }
        public string Email { get; set; }
        public string Celular { get; set; }
        public string Login { get; set; }
        public string Senha { get; set; }
        public Nullable<System.DateTime> UltimoAcesso { get; set; }
        public int UsuarioPerfilID { get; set; }
        public Nullable<int> EnderecoID { get; set; }
    
        public virtual Endereco Endereco { get; set; }
        public virtual UsuarioPerfil UsuarioPerfil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compra> Compras { get; set; }
    }
}
